### ISSUE TITLE
Error 500 when configuring Linky account

### ISSUE THREAD

**Issue by gnouts** [YunoHost-Apps/pilea_ynh#13] opened 2019-08-07 11:48 UTC
Hello,

I've got an internal server error when I press "Save" after filling up parameters.

![2019-08-07_13h47_08](https://user-images.githubusercontent.com/17988185/62620533-dcb9dd00-b919-11e9-81e3-2f43ae80e733.png)

From the log, here is what I get :

```
[2019-08-07 13:42:41] php.CRITICAL: Call to a member function removeElement() on array {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function removeElement() on array at /var/www/pilea/src/Entity/Place.php:117)"} []
[2019-08-07 13:42:41] php.CRITICAL: Call to a member function removeElement() on array {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function removeElement() on array at /var/www/pilea/src/Entity/Place.php:117)"} []
[2019-08-07 13:42:41] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function removeElement() on array" at /var/www/pilea/src/Entity/Place.php line 117 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function removeElement() on array at /var/www/pilea/src/Entity/Place.php:117)"} []
[2019-08-07 13:42:41] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function removeElement() on array" at /var/www/pilea/src/Entity/Place.php line 117 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function removeElement() on array at /var/www/pilea/src/Entity/Place.php:117)"} []
```

**Comment by SimonMellerin** [comment] 2019-08-09 10:01
Hi, thanks for reporting this

I'm currently in holidays, i'm gonna check that on my return

**Comment by Tropicao** [comment] 2019-09-02 06:38
Same here on fresh Yunohost install on Debian 9

**Comment by SimonMellerin** [comment] 2019-09-02 08:00
Hi, 
I reproduced it, 
I'm gonna push an update soon !

**Comment by Tropicao** [comment] 2019-09-04 21:53
Hey,
just to let you know that I do not see error 500 anymore since your last commit, my login seems to be accepted by Pilea. There is still some PHP critical error in date formatting :

> [2019-09-04 22:49:19] request.CRITICAL: Uncaught PHP Exception Exception: "DateTime::__construct(): Failed to parse time string (2019-31-8 23:59:59) at position 6 (1): Unexpected character" at /var/www/pilea/src/Controller/DataController.php line 37 {"exception":"[object] (Exception(code: 0): DateTime::__construct(): Failed to parse time string (2019-31-8 23:59:59) at position 6 (1): Unexpected character at /var/www/pilea/src/Controller/DataController.php:37)"} []
[2019-09-04 22:49:19] request.CRITICAL: Uncaught PHP Exception Exception: "DateTime::__construct(): Failed to parse time string (2019-31-8 23:59:59) at position 6 (1): Unexpected character" at /var/www/pilea/src/Controller/DataController.php line 176 {"exception":"[object] (Exception(code: 0): DateTime::__construct(): Failed to parse time string (2019-31-8 23:59:59) at position 6 (1): Unexpected character at /var/www/pilea/src/Controller/DataController.php:176)"} []

 I have been able to mitigate this using DateTime::createFromFormat 
`$end = $end ? \DateTime::createFromFormat('Y-d-m H:i:s', $end . ' 23:59:59') : new \DateTime();`
 
But I cannot confirm the fix yet since I cannot still see my power consumption in the interface (not a PHP expert). I'll let you know if I get anything new.

Edit : sounds like log should output "Your configuration has been properly saved" but cannot see it

**Comment by SimonMellerin** [comment] 2019-09-05 08:46
Which version of pilea do you use ? (you can see it on the configuration page of pilea)

The bug you mention is an old bug I forgot to solve, but it appears only with the default date selection, after you have chosen other date, it should disappear. You can open an other issue for this one

**Comment by Tropicao** [comment] 2019-09-05 09:03
It is v0.3.11. Ok, I will check it with other date, and open issue if relevant

**Comment by SimonMellerin** [comment] 2019-09-06 07:52
And do you still have no consumption ? no meteo data too ?

**Comment by Tropicao** [comment] 2019-09-06 08:13
Hi, still no data on my side, nor consumption neither meteo. Sorry I did not get time yet to investigate if my credentials have been properly saved, even if I do not observe error 500 anymore. I will report there as soon as I get more info on this issue (later that day or tomorrow)

**Comment by SimonMellerin** [comment] 2019-09-16 09:08
Do you still have troubles fetching data ?
If so, may be you can open a new issue, I'm gonna close this one which is solved

cheers

**Closed as completed by SimonMellerin** 2019-09-16 09:08 UTC

**Comment by Tropicao** [comment] 2019-09-16 09:50
Hi, understood. I still got issues even after last update, I will open separate issues.
