### ISSUE TITLE
Many network calls to donneespubliques.meteofrance.fr

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/pilea_ynh#7] opened 2019-02-18 13:14 UTC
I have a pi-hole installed on my server.
This is basically to block the ads but I also use it to have a quick look at the networks request from the server itself.
I noticed I have around 2.000 request per day to donneespubliques.meteofrance.fr
(and 12.000 in the last 24h)

Isn't this way too much ?

(I just have the DNS logs, so I have no idea on the urls called)

**Comment by SimonMellerin** [comment] 2019-02-19 09:58
wow thanks for this feedback

no it's not the normal behavior, i'm gonna check that

**Comment by supermamie** [comment] 2019-02-19 10:02
If I ignore the federated apps that are meant to do a lot of traffic network, the 2nd app with the biggest number of DNS request on my server is Pilea.
For the last 24h I have : 

Domain | nb requests
-- | --
donneespubliques.meteofrance.fr | 15092
espace-client-particuliers.enedis.fr | 684
www.enedis.fr | 602

**Comment by supermamie** [comment] 2019-02-19 10:05
Note : it seems I missread the logs and the previous table may be the total since Pilea was installed, I'll re-read

**Comment by supermamie** [comment] 2019-02-19 13:08
I don't really know how to read the table I copied and that seems to be for the last 24h, but for the last 30 days, I have this (this should be true)

Domain | Hits
-- | -- 
donneespubliques.meteofrance.fr | 58154
www.enedis.fr | 13142
espace-client-particuliers.enedis.fr | 10434
espace-client-connexion.enedis.fr | 6644

**Comment by SimonMellerin** [comment] 2019-02-19 14:03
ok thanks, i'm gonna check this

**Comment by supermamie** [comment] 2019-06-21 11:40
Sorry to bother (as this issue have been fixed upstream), but do you have any idea about when we will receive this ?

**Comment by SimonMellerin** [comment] 2019-06-26 14:56
Sorry, I wanted to fix this PHP version problem (#11) before doing this, and I haven't succed and completely forgot this one...

I'm gonna try to fix these issues  next week, 
thanks for the reminder

**Comment by maniackcrudelis** [comment] 2019-07-04 19:53
Hey guys, just received a phone call (!!!) from Enedis (really, that isn't a joke!) to tell me my server was crashing their own by sending too many requests.
I guess this is related to this issue.
They told me it was about 120 000 blocking requests per day

**Comment by maniackcrudelis** [comment] 2019-07-04 19:59
Sorry, my phone was doing shit...

So, they send me what they have by email. Not that much actually

> Voici ci-dessous l’erreur générée :
> `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">`
`<html><head>`
`<title>302 Found</title>`
`</head><body>`
`<h1>Found</h1>`
`<p>The document has moved <a href="/messages/inexistant.html">here</a>.</p>`
`</body></html>`
`POST /messages/inexistant.html HTTP/1.1`
`Host: espace-client-connexion.enedis.fr`
`User-Agent: User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 `Firefox/57.0`
`Accept: */*`
`HTTP/1.1 302 Found`
`Date: Thu, 04 Jul 2019 08:10:03 GMT`
`Location: /messages/inexistant.html`
`Content-Length: 209`
`Content-Type: text/html; charset=iso-8859-1`

Hopefully, they found my resume and called me, otherwise they would have banned my IP.
Which make me think this should be fix as quick as possible before other people get banned from their server.

**Comment by SimonMellerin** [comment] 2019-07-05 07:35
Waw i'm sorry,
I've no time to work on Pilea these days, but looking at Pilea commit, this issue is solved. 
I've just upgraded Pilea relaese version in pilea_ynh

**Comment by SimonMellerin** [comment] 2019-07-05 07:36
Ah, I haven't noticed the 302, that's strange :(

May be you can ask them which request leads to this 302, It can help me a lot to find where's the problem and which URL they changed

I reopen this issue

**Comment by maniackcrudelis** [comment] 2019-07-05 07:41
The only contact I have left is an email address, cyber-defense@enedis.fr, they expect an email from you, so don't hesitate.
I removed the app for now, I hope it would be back soon.

**Comment by SimonMellerin** [comment] 2019-07-05 08:56
Well, I've just send them an email.

Normally, with the version i've just pushed, It should be ok

**Comment by supermamie** [comment] 2019-07-05 12:14
It should be OK if I were able to upgrade :stuck_out_tongue: 

> Les applications suivantes n'ont pas été mises à jour : pilea
> 
> L’opération 'Mettre à jour l’application 'pilea'' a échouée ! Pour avoir de l’aide, merci de fournir le journal historisé complet de l’opération en cliquant ici
> 
> Impossible de mettre à jour pilea
> 
> The app was restored to the way it was before the failed upgrade.
> 
> Remove the user pilea
> 
> /etc/cron.d/pilea wasn't deleted because it doesn't exist.
> 
> Removing database pilea
> 
> Upgrade failed.
> 
> !!
> 
> pilea's script has encountered an error. Its execution was cancelled.
> 
> !!
> 
> doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] []
> 
> 00.php on line 35
> 
> , string given, called in /var/www/pilea/src/Migrations/Version201902131459
> 
> Argument 1 passed to App\Entity\Place::setCreator() must be of the type int
> 
> In Place.php line 88:
> 
> 14:10:02 ERROR [console] Error thrown while running command "--no-interaction --env=prod doctrine:migrations:migrate -n". Message: "Argument 1 passed to App\Entity\Place::setCreator() must be of the type int, string given, called in /var/www/pilea/src/Migrations/Version20190213145900.php on line 35" ["exception" => TypeError { …},"command" => "--no-interaction --env=prod doctrine:migrations:migrate -n","message" => "Argument 1 passed to App\Entity\Place::setCreator() must be of the type int, string given, called in /var/www/pilea/src/Migrations/Version20190213145900.php on line 35"]
> 
> Reload the service nginx
> 
> Mise à jour de l’application pilea …

I'll try the "warrior upgrade" like last time (mysqldump, uninstall, install, restore database) this weekend

**Comment by supermamie** [comment] 2019-07-05 12:23
Note : I have the full log but I am not OK to publish it online, it seems to contain many informations (but I can send it privately to @SimonMellerin if needed)

**Comment by SimonMellerin** [comment] 2019-07-05 12:36
Sorry for that should be ok now

**Comment by supermamie** [comment] 2019-07-05 18:20
Update done, more infos about network tomorrow 🙂

**Comment by supermamie** [comment] 2019-07-06 07:31
As you can see, there are a few "calm" hours, then it start again.

![IMG_20190706_091850](https://user-images.githubusercontent.com/693751/60753272-02c52800-9fd0-11e9-8b66-8a0e26a1be87.jpg)
(The base level of ~200 request / 10min are requests to donneespubliques.meteofrance.fr )

**Comment by supermamie** [comment] 2019-07-06 07:32
And I just noticed that those calm hours are between my failed upgrade and the successful one.

**Comment by SimonMellerin** [comment] 2019-07-09 13:58
hum, should be those 302.. 
I'm gonna try to find which request is responsible, and with some luck, I'll have a reply from enedis

**Comment by SimonMellerin** [comment] 2019-07-11 16:24
@supermamie ,

Can you tell me if one of meteo data is always missing like you never have rain or humidity ?
Maybe it's related to https://github.com/SimonMellerin/Pilea/issues/16

Pilea try to get data it doesn't has yet, if it see there's no rain data fo 1 month, it gonna try every 10 min to get that data.

I have to update this to tell that if we have at least one meteo data then we shouldn't go look for more

**Comment by supermamie** [comment] 2019-07-12 09:44
I have all weather information available (T°, rain, clouds)
I just checked the pi-hole log and now I am close to 400 (380) logs per 10min to donneespubliques.meteofrance.fr

**Comment by supermamie** [comment] 2019-07-19 13:42
I was looking on the monthly usage on my server and noticed something strange with MySQL
![image](https://user-images.githubusercontent.com/693751/61539041-e1862200-aa3a-11e9-99b4-406919f0e81f.png)

The moment withour usage is the day when I had a problem with Pilea, so I am pretty sure (but not 100% sure) that the load is due to pilea.

Just to be sure, I looked at the DNS logs and now I am at 600 request / 10 minutes.

And I still have the weather available in Pilea.

I don't know if any of this helps, but I don't want Pilea to become the most heavy service on my server :disappointed:

**Comment by supermamie** [comment] 2019-07-23 09:04
Today : more than 70 request per minute (706/10min)

I think I'll have to uninstall pilea, I can not spam donneespubliques.meteofrance.fr like that anymore :cry: 

edit : I just blocked this domain in the DNS, so I'll still have the electric consumption and not the weather, I'll unblock it when this will be fixed

**Comment by SimonMellerin** [comment] 2019-07-23 09:50
I'm really sorry to see that :/ 

It's hard to find time in summer to work on Pilea.. so you right, do a backup of your pilea instance and uninstall it untill I can correct this bug

Do you have phpmyadmin or can you connect to mysql by CLI ? Can you give the result of this request ? (there's no personal data in it, just the last time each data has been fetched)
```
SELECT feed_data.data_type, max(data_value.date) FROM `data_value` join feed_data on feed_data.id = data_value.feed_data_id group by feed_data.id 
```

**Comment by supermamie** [comment] 2019-07-23 14:43
Here it is :
```
+-----------------+----------------------+
| data_type       | max(data_value.date) |
+-----------------+----------------------+
| CONSO_ELEC      | 2019-07-22 23:00:00  |
| TEMPERATURE     | 2019-07-22 00:00:00  |
| TEMPERATURE_MIN | 2019-07-22 00:00:00  |
| TEMPERATURE_MAX | 2019-07-22 00:00:00  |
| DJU             | 2019-06-22 00:00:00  |
| PRESSURE        | 2019-07-22 00:00:00  |
| HUMIDITY        | 2019-07-22 00:00:00  |
| NEBULOSITY      | 2019-07-21 00:00:00  |
| RAIN            | 2019-07-21 00:00:00  |
+-----------------+----------------------+
9 rows in set (0.03 sec)
```

**Comment by supermamie** [comment] 2019-07-23 14:46
So it seems I can just enable this between 23:00 and 00:00 to still have the data, and without spamming meteofrance ?

**Comment by SimonMellerin** [comment] 2019-07-23 15:43
No, it says for example that the last data you have for temperature is the temperature for '2019-07-22 00:00:00'

But it shows that pilea seems to have trouble with the DJU data (which is a calculted data from temperatures data) (the last DJU calculated was for o 2019-06-22) 
May be that comes from here !

Can you send me one of your last log files (/var/www/pilea/var/log/prod-2019-07-22.log for example) (I don't think there's sensitive data in it, but if you want, send me it via the Yunohost forum)

**Comment by supermamie** [comment] 2019-07-24 09:39
There is nothing special in it, just the informations about the pages I looked at (and 2 warnings)

Here is the complete log for 2019-07-23 (there was no log for 2019-07-22, the last one was 2019-07-19)

In 2019-07-23, the 2 warnings are exactly the same line, at the same timestamp :
`[2019-07-23 16:45:29] php.WARNING: Warning: SessionHandler::read(): open(/var/lib/php/sessions/sess_blablablablablablablablabla, O_RDWR) failed: Permission denied (13) {"exception":"[object] (ErrorException(code: 0): Warning: SessionHandler::read(): open(/var/lib/php/sessions/sess_blablablablablablablablabla, O_RDWR) failed: Permission denied (13) at /var/www/pilea/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php:48)"} []`
(I changed the sess_xxxxxx value just in case)

in 2019-07-19, there are 2 errors (same line, same timestamp) linked to the dns block :
```log
[2019-07-19 04:42:13] console.ERROR: Error thrown while running command "pilea:fetch-data false". 
Message: "Error creating resource: [message] fopen(https://donneespubliques.meteofrance.fr/?fond=donnee_indisponible): failed to open stream: Connection timed out [file] /var/www/pilea/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php [line] 323
" {"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 0): Error creating resource: 
[message] fopen(https://donneespubliques.meteofrance.fr/?fond=donnee_indisponible): failed to open stream: Connection timed out\n
[file] /var/www/pilea/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php\n
[line] 323 at /var/www/pilea/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:52, 
RuntimeException(code: 0): Error creating resource: 
[message] fopen(https://donneespubliques.meteofrance.fr/?fond=donnee_indisponible): failed to open stream: Connection timed out\n
[file] /var/www/pilea/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php\n
[line] 323 at /var/www/pilea/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:252)",
"command":"pilea:fetch-data false",
"message":"Error creating resource: [message] fopen(https://donneespubliques.meteofrance.fr/?fond=donnee_indisponible): failed to open stream: Connection timed out\n
[file] /var/www/pilea/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php\n[line] 323"} []
```

And the 2 same warnings as in 2019-07-23


Just in case, here is the full 2019-07-23 log :
```log
[2019-07-23 16:45:29] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","_controller":"App\\Controller\\DefaultController::homepageAction"},"request_uri":"https://myserver.fr/pilea/","method":"GET"} []
[2019-07-23 16:45:29] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","_controller":"App\\Controller\\DefaultController::homepageAction"},"request_uri":"https://myserver.fr/pilea/","method":"GET"} []
[2019-07-23 16:45:29] php.WARNING: Warning: SessionHandler::read(): open(/var/lib/php/sessions/sess_blablablablablablablablabla, O_RDWR) failed: Permission denied (13) {"exception":"[object] (ErrorException(code: 0): Warning: SessionHandler::read(): open(/var/lib/php/sessions/sess_blablablablablablablablabla, O_RDWR) failed: Permission denied (13) at /var/www/pilea/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php:48)"} []
[2019-07-23 16:45:29] php.WARNING: Warning: SessionHandler::read(): open(/var/lib/php/sessions/sess_blablablablablablablablabla, O_RDWR) failed: Permission denied (13) {"exception":"[object] (ErrorException(code: 0): Warning: SessionHandler::read(): open(/var/lib/php/sessions/sess_blablablablablablablablabla, O_RDWR) failed: Permission denied (13) at /var/www/pilea/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php:48)"} []
[2019-07-23 16:45:29] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:29] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-repartition". {"route":"data-api-repartition","route_parameters":{"_route":"data-api-repartition","start":"2019-07-01","end":"2019-07-22","_controller":"App\\Controller\\DataController::getRepartionAction","dataType":"conso_elec","repartitionType":"year_v"},"request_uri":"https://myserver.fr/pilea/data/conso_elec/repartition/year_v/2019-07-01/2019-07-22","method":"GET"} []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-repartition". {"route":"data-api-repartition","route_parameters":{"_route":"data-api-repartition","start":"2019-07-01","end":"2019-07-22","_controller":"App\\Controller\\DataController::getRepartionAction","dataType":"conso_elec","repartitionType":"year_v"},"request_uri":"https://myserver.fr/pilea/data/conso_elec/repartition/year_v/2019-07-01/2019-07-22","method":"GET"} []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-sum". {"route":"data-api-sum","route_parameters":{"_route":"data-api-sum","start":"2019-07-01","end":"2019-07-22","_controller":"App\\Controller\\DataController::getSumAction","dataType":"conso_elec"},"request_uri":"https://myserver.fr/pilea/data/conso_elec/sum/2019-07-01/2019-07-22","method":"GET"} []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-sum". {"route":"data-api-sum","route_parameters":{"_route":"data-api-sum","start":"2019-07-01","end":"2019-07-22","_controller":"App\\Controller\\DataController::getSumAction","dataType":"conso_elec"},"request_uri":"https://myserver.fr/pilea/data/conso_elec/sum/2019-07-01/2019-07-22","method":"GET"} []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-repartition". {"route":"data-api-repartition","route_parameters":{"_route":"data-api-repartition","start":"2019-07-01","end":"2019-07-22","_controller":"App\\Controller\\DataController::getRepartionAction","dataType":"temperature","repartitionType":"year_v"},"request_uri":"https://myserver.fr/pilea/data/temperature/repartition/year_v/2019-07-01/2019-07-22","method":"GET"} []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-repartition". {"route":"data-api-repartition","route_parameters":{"_route":"data-api-repartition","start":"2019-07-01","end":"2019-07-22","_controller":"App\\Controller\\DataController::getRepartionAction","dataType":"temperature","repartitionType":"year_v"},"request_uri":"https://myserver.fr/pilea/data/temperature/repartition/year_v/2019-07-01/2019-07-22","method":"GET"} []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-repartition". {"route":"data-api-repartition","route_parameters":{"_route":"data-api-repartition","start":"2019-06-01","end":"2019-06-30","_controller":"App\\Controller\\DataController::getRepartionAction","dataType":"conso_elec","repartitionType":"year_v"},"request_uri":"https://myserver.fr/pilea/data/conso_elec/repartition/year_v/2019-06-01/2019-06-30","method":"GET"} []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-repartition". {"route":"data-api-repartition","route_parameters":{"_route":"data-api-repartition","start":"2019-06-01","end":"2019-06-30","_controller":"App\\Controller\\DataController::getRepartionAction","dataType":"conso_elec","repartitionType":"year_v"},"request_uri":"https://myserver.fr/pilea/data/conso_elec/repartition/year_v/2019-06-01/2019-06-30","method":"GET"} []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-sum". {"route":"data-api-sum","route_parameters":{"_route":"data-api-sum","start":"2019-06-01","end":"2019-06-30","_controller":"App\\Controller\\DataController::getSumAction","dataType":"conso_elec"},"request_uri":"https://myserver.fr/pilea/data/conso_elec/sum/2019-06-01/2019-06-30","method":"GET"} []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-sum". {"route":"data-api-sum","route_parameters":{"_route":"data-api-sum","start":"2019-06-01","end":"2019-06-30","_controller":"App\\Controller\\DataController::getSumAction","dataType":"conso_elec"},"request_uri":"https://myserver.fr/pilea/data/conso_elec/sum/2019-06-01/2019-06-30","method":"GET"} []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-sum". {"route":"data-api-sum","route_parameters":{"_route":"data-api-sum","start":"2019-06-01","end":"2019-06-30","_controller":"App\\Controller\\DataController::getSumAction","dataType":"dju"},"request_uri":"https://myserver.fr/pilea/data/dju/sum/2019-06-01/2019-06-30","method":"GET"} []
[2019-07-23 16:45:30] request.INFO: Matched route "data-api-sum". {"route":"data-api-sum","route_parameters":{"_route":"data-api-sum","start":"2019-06-01","end":"2019-06-30","_controller":"App\\Controller\\DataController::getSumAction","dataType":"dju"},"request_uri":"https://myserver.fr/pilea/data/dju/sum/2019-06-01/2019-06-30","method":"GET"} []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-07-23 16:45:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
```

**Comment by SimonMellerin** [comment] 2019-07-24 12:26
I've may be an idea, can you give the result of 
`SELECT feed_data.data_type, data_value.date, data_value.value FROM `data_value` join feed_data on feed_data.id = data_value.feed_data_id where data_value.date = '2019-06-22 00:00:00' and feed_data.data_type like "TEMPERATURE%" group by feed_data.id `

**Comment by supermamie** [comment] 2019-07-24 12:33
```sql
+-----------------+---------------------+-------+
| data_type       | date                | value |
+-----------------+---------------------+-------+
| TEMPERATURE     | 2019-06-22 00:00:00 |  20.3 |
| TEMPERATURE_MIN | 2019-06-22 00:00:00 |  14.9 |
| TEMPERATURE_MAX | 2019-06-22 00:00:00 |    25 |
+-----------------+---------------------+-------+
```

Same result with 2019-07-22 (in case it was an error to ask for june)

```sql
+-----------------+---------------------+-------+
| data_type       | date                | value |
+-----------------+---------------------+-------+
| TEMPERATURE     | 2019-07-22 00:00:00 |  30.1 |
| TEMPERATURE_MIN | 2019-07-22 00:00:00 |  22.9 |
| TEMPERATURE_MAX | 2019-07-22 00:00:00 |  36.8 |
+-----------------+---------------------+-------+
```

Just for fun, I replaced `data_value.date = '2019-06-22 00:00:00'` by `data_value.date LIKE '2019-06-22%'` and got the same results (only T° available is at 00:00:00)

**Comment by SimonMellerin** [comment] 2019-07-24 13:55
Well that not what I though

I can't figure out why pilea can calculate your DJU since 2019-06-22 !
But I think your problem comes from here : as pilea can't find data for DJU since 06-22, it tries to get data from meteo france for each day from this date, each 10 minutes.

Ah i'm stupdi, if you have DJU the 06-22, then it's the 06-23 that pilea can't calculates ! Can you try :

`SELECT feed_data.data_type, data_value.date, data_value.value FROM data_valuejoin feed_data on feed_data.id = data_value.feed_data_id where data_value.date = '2019-06-23 00:00:00' and feed_data.data_type like "TEMPERATURE%" group by feed_data.id`

>  Just for fun, I replaced data_value.date = '2019-06-22 00:00:00' by data_value.date LIKE '2019-06-22%' and got the same results (only T° available is at 00:00:00)

Pilea keeps only 1 meteo data per day for each type of data while it keeps one data per hour for electricity. It's because we can only get data per 3 hours from meteo france and it complicated a lot lot,of thing if i wanted to keep all the data :) so I choose to only keep one !

I update the DJU calculation on Pilea, can you try to update your pilea instance, with some louck, it will fix your problem !

**Comment by supermamie** [comment] 2019-07-24 14:21
I'll update as soon as the yunohost app list will be updated (0.3.4 is still considered the last version).

I just tried the request to get the datas for 2019-06-22, 23, 24 and I have values for each of them.
In the weather tab of pilea, I have weather data for every day since many months
![image](https://user-images.githubusercontent.com/693751/61800788-f2b1a300-ae2d-11e9-8fb6-bdb35696ee9d.png)

On the other hand, 2019-06-23 is the day when DJU started to become null, we'll see if the new way of calcul can fix something :smiley: 
![image](https://user-images.githubusercontent.com/693751/61801054-6ce22780-ae2e-11e9-9d49-c39d296275ba.png)

I did the request again without the filter on TEMPERATURE% and there is the DJU column missing
```sql
+-----------------+---------------------+---------+
| data_type       | date                | value   |
+-----------------+---------------------+---------+
| CONSO_ELEC      | 2019-06-22 00:00:00 |   4.748 |
| TEMPERATURE     | 2019-06-22 00:00:00 |    20.3 |
| TEMPERATURE_MIN | 2019-06-22 00:00:00 |    14.9 |
| TEMPERATURE_MAX | 2019-06-22 00:00:00 |      25 |
| DJU             | 2019-06-22 00:00:00 |       1 |
| PRESSURE        | 2019-06-22 00:00:00 | 99924.3 |
| HUMIDITY        | 2019-06-22 00:00:00 |    66.7 |
| NEBULOSITY      | 2019-06-22 00:00:00 |      95 |
| CONSO_ELEC      | 2019-06-23 00:00:00 |   4.659 |
| TEMPERATURE     | 2019-06-23 00:00:00 |    24.9 |
| TEMPERATURE_MIN | 2019-06-23 00:00:00 |    16.1 |
| TEMPERATURE_MAX | 2019-06-23 00:00:00 |    31.9 |
| PRESSURE        | 2019-06-23 00:00:00 | 99517.1 |
| HUMIDITY        | 2019-06-23 00:00:00 |    55.1 |
+-----------------+---------------------+---------+
```
(there is also nebulosity missing, which may be linked to https://github.com/SimonMellerin/Pilea/issues/16 )


Thanks a lot to find some time during the summer to work on this :+1:

**Comment by supermamie** [comment] 2019-07-26 06:36
Pilea updated, so I unblocked donneespubliques.meteofrance.fr in the DNS.
The T° were retreived, but I now have ~800 request/10min

It never stops growing :scream:

**Comment by SimonMellerin** [comment] 2019-07-29 08:28
Huum :/

Try to manually insert a DJU value for yesterday with :

`INSERT INTO data_value
(feed_data_id, date, value, frequency, week_day, week, month, year) 
VALUES
(
  (SELECT id FROM feed_data WHERE data_type = "DJU"), 
  '2019-07-28 00:00:00', 
  '0',
  '2',
  '7',
  '30',
  '7',
  '2019',
);`

**Comment by supermamie** [comment] 2019-07-29 08:31
Just for yesterday or for every day without DJU ?
(I've done it for yesterday, I'll check the DNS this afternoon)

**Comment by SimonMellerin** [comment] 2019-07-29 08:37
If data are founds for yesterday, Pilea will not try to fetch data

**Comment by supermamie** [comment] 2019-07-29 11:44
No more calls since I added DJU for yesterday :smiley:

**Comment by SimonMellerin** [comment] 2019-07-29 13:19
hum now, I've to find why your pilea instance won't calculate your DJU properly !

**Comment by supermamie** [comment] 2019-07-30 07:13
Just in case someone have the same problem, here is my request I'll cron to run each morning at 1h00 to fill every empty DJU with zero and a copy of the values from the same day from the TEMPERATURE line (to get the right date, day-of-week, etc...) :
`INSERT INTO data_value (feed_data_id, value, date, frequency, week_day, week, month, year)
SELECT '5', '0', date, frequency, week_day, week, month, year FROM data_value WHERE feed_data_id = '2' AND date NOT IN (SELECT date FROM data_value WHERE feed_data_id = '5');`

Please note that I hard-coded 5 and 2 which are the ids for DJU (5) and TEMPERATURE (2) in my database, I have no idea if it is the same everywhere.

To get those : 
`SELECT id FROM feed_data WHERE data_type = "DJU";`
`SELECT id FROM feed_data WHERE data_type = "TEMPERATURE";`

Side note : I noticed I sometime have `NULL` values in week_day or hour (I have zeros, and also some nulls)

**Comment by SimonMellerin** [comment] 2019-08-01 12:14
I've just updated pilea, your problem should be solved + I made a migration to rebuild data (you should have lot of 0 nebulosity or DJU missing) 

I propose that we close this ticket in few days when we can see if the problem is actually solved ;)

**Comment by supermamie** [comment] 2019-08-02 15:38
Pilea updated, and DNS log flushed.
I already notice a nice side-effect : now the average values are calculated with all days, not only those with a >0 value (which is a big difference with nebulosity which is >90% or 0, now the average is ~60)

**Comment by supermamie** [comment] 2019-08-05 09:25
I think this caused another bug :( 
I have a negative electric consumption since I updated.
(-1kWh every day)

I'll be happy if this was true, but it is not and I wont receive money from my provider :euro: 

![image](https://user-images.githubusercontent.com/693751/62453898-9fb3e600-b773-11e9-9711-e5747e51c4a7.png)

**Comment by SimonMellerin** [comment] 2019-08-09 10:01
hum :/

I'm currently in holidays, i'm gonna check that on my return.

But the good news is : the data can be rebuilt so there will be no data loss !

**Comment by supermamie** [comment] 2019-08-09 13:41
Enjoy your holidays, I can survive a few months without data :sun_with_face:

**Comment by SimonMellerin** [comment] 2019-08-20 18:15
Someone has opened an issue in the pilea's repo about this problem (https://github.com/SimonMellerin/Pilea/issues/21)

As the original problem of this issue is solved, May be we can close this one and reopen a new one about this particular problem and then link it to https://github.com/SimonMellerin/Pilea/issues/21

**Closed as completed** 2019-08-27 07:23 UTC
